TOPDIR = ../..
include $(TOPDIR)/Make/makedefs

CXXFILES =\
	osgdem.cpp\


LIBS     += -losgViewer -lvpb -losgFX -losgDB -losgText -losgUtil -losg $(GDAL_LIBS) $(GL_LIBS) $(X_LIBS) $(OTHER_LIBS) 

EXEC = osgdem

INC += $(X_INC)

include $(TOPDIR)/Make/makerules
